north_america: 
  - アメリカ
  - エルサルバドル
  - カナダ
  - キューバ
  - グアテマラ
  - コスタリカ
  - ジャマイカ
  - ドミニカ共和国
  - パナマ
  - ハイチ
  - バハマ
  - ベリーズ
  - ホンジュラス
  - メキシコ
south_america:
  - アルゼンチン
  - ウルグアイ
  - エクアドル
  - コロンビア
  - ジャマイカ
  - チリ
  - ブラジル
  - ペルー
  - ベネズエラ
  - ボリビア
  - ガイアナ
  - スリナム
  - パラグアイ
asia:
  - インド
  - インドネシア
  - カンボジア
  - シンガポール
  - スリランカ
  - タイ
  - 韓国
  - 中国
  - 台湾
  - ネパール
  - パキスタン
  - バングラディッシュ
  - 東ティモール
  - フィリピン
  - ブルネイ
  - ベトナム
  - マレーシア
  - ミャンマー
  - モルディブ
  - モンゴル
  - ラオス
middle_east:
  - アフガニスタン
  - アラブ首長国連邦
  - イエメン
  - イスラエル
  - イラク
  - イラン
  - オマーン
  - カタール
  - クウェート
  - サウジアラビア
  - バーレーン
  - トルコ
  - ヨルダン
  - レバノン
oceania:
  - オーストラリア
  - ニュージーランド
  - フィジー
  - パプアニューギニア
  - ミクロネシア
  - サモア
  - トンガ
  - バヌアツ
  - パラオ
  - キリバス
  - グアム
  - ニューカレドニア
  - ツバル
  - マーシャル諸島
europe:
  - オーストリア
  - ベルギー
  - ブルガリア
  - クロアチア
  - チェコ
  - キプロス
  - デンマーク
  - エストニア
  - フィンランド
  - フランス
  - ドイツ
  - ギリシャ
  - ハンガリー
  - アイルランド
  - イタリア
  - ラトビア
  - リトアニア
  - ルクセンブルク
  - マルタ
  - オランダ
  - ポーランド
  - ポルトガル
  - ルーマニア
  - スロバキア
  - スロベニア
  - スペイン
  - スウェーデン
  - マケドニア
  - スイス
  - セルビア
  - モンテネグロ
  - ドイツ
  - ノルウェー
  - バチカン市国
  - アイスランド
  - ジョージア
africa:
  - 南アフリカ
  - ナイジェリア
  - ケニア
  - ガーナ
  - タンザニア
  - エチオピア
  - コンゴ
  - モロッコ
  - セネガル
  - ウガンダ
  - マダガスカル
  - コートジボワール
  - アルジェリア
  - カメルーン
  - スーダン
  - ルワンダ
  - ジンバブエ
  - ザンビア
  - チュニジア
  - リベリア
  - ギニア
  - ボツワナ
  - リビア
  - 中央アフリカ
  - トーゴ
  - ジブチ
  - ベナン
  - コンゴ
  - モーリシャス
  - 南スーダン
  